const express = require('express')
const bodyParser = require('body-parser')
const cookieParser = require('cookie-parser')
const app = express()
const {reslove} = require('path')
const server = require('http').Server(app)
const userRouter = require('./router/user')
// require('./db/index')
app.use('/', express.static(reslove(__dirname, '../dist')))
app.use(cookieParser())
app.use(bodyParser.json())
app.use('/api', userRouter)
server.listen(9111, function() {
  console.log('Node app start at port 9111')
})
